### ISSUE TITLE
bad button resolution in about screen

### ISSUE THREAD

**Issue by N3koSempai** [n000tavailable/tunedetective#12]
the buttons for redirect to this repository  have a bad representation. the two in the bottom

![screenshot](https://github.com/n000tavailable/tunedetective/assets/43711237/865a8e5e-fb0b-4651-b9c1-5ab651785599)

**Comment by n000tavailable** [comment]
Which size is your screen?

**Comment by N3koSempai** [comment]
![prop](https://github.com/n000tavailable/tunedetective/assets/43711237/b091278b-ee99-4581-8d7a-a7dfd0c88b6b)

**Comment by n000tavailable** [comment]
something is wrong. your device is actually quite big, so you should have enough space for everything displayed. are you using different display settings?
