### ISSUE TITLE
mishandling error response or timeout from deezer.

### ISSUE THREAD

**Issue by N3koSempai** [n000tavailable/tunedetective#13]
because of my IP deezer blocks me. so when i hit fetch the data. the application shows the progress bar and stays black empty without showing any notification.

suggestion: add a timeout for the request to deezer and show some warning to the user.

**Comment by n000tavailable** [comment]
I'm not able to reproduce this. Can you share more information. Are you using something like tor?

**Comment by N3koSempai** [comment]
i am from cuba . many service block my country. deezer too.
https://github.com/n000tavailable/tunedetective/assets/43711237/7c2dc7e9-0956-4918-b527-8b8f31b68f5d

**Comment by n000tavailable** [comment]
all right. if deezer is not available for you, you have to use a vpn or something similar, like you already do. so for me the problem is solved. maybe i write a note in the readme
