### ISSUE TITLE
Add "Get it on Accrescent" to README

### ISSUE THREAD

**Issue by lazytownfan** [n000tavailable/tunedetective#15]
### Feature description

I would like to see the "Get it on Accrescent" button added to the README, as described in Accrescent's [documentation](https://accrescent.app/docs/guide/publish/post-approval.html) after approval.

This would help users know with certainty that TuneDetective is officially present on Accrescent.

(I would've made a PR, though it seems that Accrescent makes the necessary HTML code available only to approved app uploaders via the Accrescent site dashboard.)

**Comment by n000tavailable** [comment]
thx, added!
