### ISSUE TITLE
nothing?

### ISSUE THREAD

**Issue by Wjxfi** [n000tavailable/tunedetective#2]
![006e7c2f-a12e-4119-b3fc-1fbccb5351f0.jpg](https://github.com/n000tavailable/tunedetective/assets/113500363/11ef4894-6c50-4715-8a0d-d81aad43b210)

**Comment by n000tavailable** [comment]
Hey, what seems to be the problem?

**Comment by n000tavailable** [comment]
Can you tell me which artist you're looking for and whats supposed to be there instead?
Should be an API issue.But let me check.

**Comment by n000tavailable** [comment]
can you provide the deezer artist link for those?

**Comment by n000tavailable** [comment]
Since there is no response or activity from the person who opened the issue, I deemed it appropriate to close it.
