### ISSUE TITLE
Some artists only show one song.

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [n000tavailable/tunedetective#4]
First of all, this app is great. One issue tho. Some artists (sodikken in this example) only show one song, not there catalog!

![Screenshot_20230610-133751.png](https://github.com/n000tavailable/tunedetective/assets/123305689/011767c5-db40-459b-b8bd-ea830f5fb752)

**Comment by n000tavailable** [comment]
Thanks :)

I gonna take a look. Can you provide me the deezer artist link?

**Comment by TeaEndsAcronyms** [comment]
Oh ok!
