### ISSUE TITLE
Fastlane short_description.txt too long

### ISSUE THREAD

**Issue by IzzySoft** [n000tavailable/tunedetective#6]
Fastlane `short_description.txt` is limited to 80 chars, everything after that is simply truncated. Yours currently has 132 chars and thus will be cut in the middle (probably even in the middle of a word). Could you please adjust it accordingly? Thanks!

**Comment by n000tavailable** [comment]
Thanks for pointing this out . Sure, I will do today

**Comment by n000tavailable** [comment]
https://github.com/n000tavailable/tunedetective/commit/8a7bcc1026c285db60beb865cc87d3889fcd4b53

**Comment by IzzySoft** [comment]
Thanks! That was fast :star_struck:
