### ISSUE TITLE
Notifications bug

### ISSUE THREAD

**Issue by ViktorKahu** [n000tavailable/tunedetective#7]
At the moment, there is a permanent notification that says "click on me to set up notifications".

When you click on it, half the time it will display a blank screen, the other half of the time it will just open the app that does not give you much options in the way of "setting up notifications", and nothing changes.

**Comment by n000tavailable** [comment]
> At the moment, there is a permanent notification that says "click on me to set up notifications".

That's correct. You can hide that notification later.


> When you click on it, half the time it will display a blank screen, the other half of the time it will just open the app that does not give you much options in the way of "setting up notifications", and nothing changes.

If you don't have any searched artists, the page will be blank. After you searched for one or multiple artists you'll see the latest releases of the artists. Now the app will look for new releases every hour.

You can hide the "click on me to set up notifications" after all that via a long press on the notification. Click on the settings icon and untoggle the "hide me" channel.

**Comment by n000tavailable** [comment]
Let me know if there are still some questions
