### ISSUE TITLE
App Crashes at Launch (fixed) and crashes on android 10 (unsolved)

### ISSUE THREAD

**Issue by tdadvocate** [n000tavailable/tunedetective#8]
The app crashes the moment I attempt to open. This occurs on at least 1.5 and 1.6 of the app. I am experiencing this issue on a Samsung Galaxy Fold 4 running Samsung One UI 5.1 Android 13 Version F936USQS2CWD9 /
F936UOYN2CWD9 / F936USQS2CWD9

**Comment by n000tavailable** [comment]
Hey, weird that this happens. did you reinstall the app?

If not do this once as I have changed the database. if this does not fix the error, send me a log file if possible

**Comment by n000tavailable** [comment]
Please let me know if the fix works

**Comment by n000tavailable** [comment]
fixed in v1.7. tested on stock android and oneui. 

https://github.com/n000tavailable/tunedetective/releases/tag/v.17

**Comment by kopalqude** [comment]
I have the same issue; app crashes on startup. Occurs on v1.8, v1.9, v2.0 but does not occur on v1.7. I reinstalled the apk each time.
The device I am using is Nokia TA-1005 running Android 10 (Android One).

**Comment by n000tavailable** [comment]
can you provide me a log?

**Comment by n000tavailable** [comment]
your problem seems to be different. i tested it on an emulator and had the same result.

it seems that I use material you colors that do not exist on android 10.

don't know what to do now, abandon material you elements?

**Comment by tdadvocate** [comment]
> your problem seems to be different. i tested it on an emulator and had the same result.
> 
> it seems that I use material you colors that do not exist on android 10.
> 
> don't know what to do now, abandon material you elements?

I think there is a way to tell it for Android 10 to use a default colour scheme, but idk for certain. The only other options I could think of are to remove Android 10 compatibility or remove Material You. I didn't even think MY came about until Android 11 or 12 so that would make sense as to why it doesn't exist.

**Comment by n000tavailable** [comment]
@kopalqude test this one, it worked on my emulator
[app-release.zip](https://github.com/n000tavailable/tunedetective/files/11850456/app-release.zip)

**Comment by kopalqude** [comment]
> @kopalqude test this one, it worked on my emulator [app-release.zip](https://github.com/n000tavailable/tunedetective/files/11850456/app-release.zip)

Seems to be fixed with this one, the app is launching now, thanks.
