### ISSUE TITLE
[Suggestion] Customisable Fetch Timer

### ISSUE THREAD

**Issue by tdadvocate** [n000tavailable/tunedetective#9]
15 minutes is honestly probably way too often for the vast majority of people. It would be nice to have options to adjust this. Maybe options of 1 week, 5 days, 3 days, 1 day, 12 hours, 6 hours, 3 hours, 1 hour, 30 minutes, and 15 minutes. That would give the most variety without getting excessive. This would also greatly reduce the battery usage and drain that the app will cause. Checking every 15 minutes would destroy battery life.

**Comment by tdadvocate** [comment]
> Do background fetches work for you? because they don't seem to work for me. or only sometimes after a very long delay time.
> 
> i am thinking about removing this function if I don't get it working right.

I believe so. I am getting notifications every 15-30 minutes, so I would assume that they are functioning. I just cleared one, so I will try to keep tabs on how often I'm at least getting the alerts. I obviously don't know any artists releasing anything anytime soon to actually test if it is pulling data, though, unfortunately.

**Comment by tdadvocate** [comment]
Update, I have continued to receive a notification every 15 minutes for the last hour. So it's definitely at least calling the notifications check.

**Comment by n000tavailable** [comment]
thank you for keeping an eye on it.
i will specify 60 minutes in the next update

**Comment by n000tavailable** [comment]
The user can in the next version (2.1) specify the interval time in minutes itself.
i will add it when everything seems to work, 1, 2 and 5 minutes have worked. everything else i have not tested, but i will

[https://github.com/n000tavailable/tunedetective/commit/228b2bb4b7761fa360a4817653b283bedaddf6a5](url)
